name: Windows-Tests

on: [push, pull_request, workflow_dispatch]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_NO_TESTS_ACTION: error

jobs:
  build-and-test:
    strategy:
      fail-fast: false

    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v7

      - name: Check Visual Studio generator
        shell: pwsh
        run: cmake --help | Select-String "Visual Studio 18 2026"

      - name: Configure
        run: cmake -S . -B build -DENABLE_TESTS=ON -DENABLE_BENCHMARKS=OFF -G "Visual Studio 18 2026"

      - name: Build
        run: cmake --build build --config Release

      - name: Tests
        run: ctest --test-dir build -C Release